<?xml version="1.0"?>
<!-- あとでdynamixel descriptionを作ってそこにれる -->
<robot name=" dynamixel-XM430" xmlns:xacro="http://ros.org/wiki/xacro">\
	<xacro:macro name="servo_XM430" params="name:='__defalut__' parent child fixed_plane:=bottom fixed_angle:=0 center_child:=false">

        <xacro:if value="${name == '__defalut__'}">
		    <xacro:property name="joint_name" value="${child}" />
        </xacro:if>
        <xacro:unless value="${name == '__defalut__'}">
		    <xacro:property name="joint_name" value="${name}" />
        </xacro:unless>

        <xacro:include filename="$(find dynamixel_description)/urdf/_XM430.gazebo.xacro"/>

        <!-- STL, daeファイルへの相対パス -->
		<xacro:property name="path_to_mesh" value="meshes/XM430_idler.stl" />
        <!-- 各辺の中点が原点となるように変換 -->
		<xacro:property name="visual_origin"> <origin xyz="${0} ${L_y_hone} ${0}" rpy="${0} ${0} ${0}" /> </xacro:property>
        <!-- 各辺の中点を原点としたときのホーン中心の座標 -->
		<xacro:property name="L_x_hone" value="${ 0.0/1000}" /> <!-- unit [m] --> <!-- converted from [mm] -->
		<xacro:property name="L_y_hone" value="${35.25/1000-W_y/2}" /> <!-- unit [m] --> <!-- converted from [mm] -->
		<xacro:property name="L_z_hone" value="${19.0/1000}" /> <!-- unit [m] --> <!-- converted from [mm] -->
		<xacro:property name="W_x" value="${28.5/1000}" /> <!-- unit [m] --> <!-- converted from [mm] -->
		<xacro:property name="W_y" value="${46.5/1000}" /> <!-- unit [m] --> <!-- converted from [mm] -->
		<xacro:property name="W_z" value="${34.0/1000}" /> <!-- unit [m] --> <!-- converted from [mm] -->
		<xacro:property name="no_load_speed" value="${66*(2*pi/60)}" /> <!-- unit [rad/sec] --> <!-- converted from [rev/min] -->
		<xacro:property name="stall_torque"  value="${8.9}" /> <!-- unit [Nm] -->
		<xacro:property name="mass"  value="${165/1000}" /> <!-- unit [kg] --> <!-- converted from [g] -->
		<xacro:property name="inertia"> <!-- unit [kg*m^@] --> <!-- converted from [g*mm^2] -->
			<inertia ixx="${72456.754/1000000000}"  ixy="${-128.62012/1000000000}" ixz="${-174.27089/1000000000}" 
			                                        iyy="${ 38622.228/1000000000}" iyz="${-8272.2282/1000000000}" 
			                                                                       izz="${ 60707.131/1000000000}" /> 
		</xacro:property>


		<joint name="${joint_name}_XM430_base_connector_" type="fixed">
			<parent link="${parent}"/>
			<child link="${joint_name}_dynx_XM430"/>
			<xacro:if value="${fixed_plane == 'bottom'}">
				<origin xyz="${0} ${0} ${W_y/2}" rpy="${pi/2} ${0} ${fixed_angle}"/> <!-- 回転が先 -->
			</xacro:if>
			<xacro:if value="${fixed_plane == 'top'}">
				<origin xyz="${0} ${0} ${-W_y/2}" rpy="${pi/2} ${0} ${fixed_angle}"/> <!-- 回転が先 -->
			</xacro:if>
			<xacro:if value="${fixed_plane == 'back'}">
				<origin xyz="${0} ${0} ${W_z/2}" rpy="${0} ${0} ${fixed_angle}"/> <!-- 回転が先 -->
			</xacro:if>
		</joint>

		<link name="${joint_name}_dynx_XM430">
			<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<mass value="${mass}"/>
				<xacro:insert_block name="inertia"/>
			</inertial>
			<visual>
				<xacro:insert_block name="visual_origin"/>
				<geometry>
					<mesh filename="package://dynamixel_description/${path_to_mesh}" />
				</geometry>
				<material name="gray">
					<color rgba="0.8 0.8 0.8 0.5"/>
				</material>
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<box size="${W_x} ${W_y} ${W_z}"/>
					<!-- <mesh filename="package://dynamixel_description/${path_to_mesh}" /> -->
				</geometry>
			</collision>
		</link>

		<joint name="${joint_name}_joint" type="continuous">
			<parent link="${joint_name}_dynx_XM430"/>
			<child link="${joint_name}_dynx_XM430_hone"/>
			<origin xyz="${L_x_hone} ${L_y_hone} ${L_z_hone}" rpy="0 0 0"/>
			<axis xyz="0 0 1"/>
			<dynamics damping="0.1"/>  
			<limit velocity="${no_load_speed}" effort="${stall_torque}" /> 
		</joint>

		<link name="${joint_name}_dynx_XM430_hone" >
			<inertial>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<mass value="0.00001" />
			<inertia
				ixx="0.00001" ixy="0.0" ixz="0.0"
				iyy="0.00001" iyz="0.0"
				izz="0.00001" />
			</inertial>
		</link>

		<joint name="${joint_name}_XM430_hone_joint_" type="fixed">
			<parent link="${joint_name}_dynx_XM430_hone"/>
			<child link="${child}"/>
			<xacro:if value="${center_child}">
				<origin xyz="0 0 ${-L_z_hone}" rpy="0 0 0"/>
			</xacro:if>
			<xacro:unless value="${center_child}">
				<origin xyz="0 0 0" rpy="0 0 0"/>
			</xacro:unless>
		</joint>

	</xacro:macro>

    <!-- フレームFR12_S102Kを装着したver -->
    <xacro:macro name="servo_XM430_FR12_S102K" params="name:='__defalut__' parent child fixed_plane:=bottom fixed_angle:=0 center_child:=false">
        <xacro:property name="path_to_mesh" value="meshes/fr12_s102.stl" />
        <!-- 各辺の中点が原点となるように変換 -->
		<xacro:property name="visual_origin"> <origin xyz="${0} ${0} ${19.5/1000-offset}" rpy="${pi} ${0} ${pi/2}" /> </xacro:property>
		<xacro:property name="offset"  value="${5.25/1000}" /> <!-- unit [kg] --> <!-- converted from [g] -->
		<xacro:property name="mass"  value="${165/1000}" /> <!-- unit [kg] --> <!-- converted from [g] -->
		<xacro:property name="inertia"> <!-- unit [kg*m^@] --> <!-- converted from [g*mm^2] -->
			<inertia ixx="${ 1999.314/1000000000}"  ixy="${    0.0  /1000000000}" ixz="${     0.0  /1000000000}" 
			                                        iyy="${ 2690.794/1000000000}" iyz="${     0.0  /1000000000}" 
			                                                                       izz="${ 1440.750/1000000000}" /> 
		</xacro:property>

        <joint name="${name}_XM430_FR12_S102K_connect_" type="fixed">
			<parent link="${parent}"/>
			<child link="${name}_fr_FR12_S102K_"/>
            <origin xyz="${0} ${0} ${offset}" rpy="${0} ${0} ${fixed_angle}"/> <!-- 回転が先 -->
		</joint>

		<link name="${name}_fr_FR12_S102K_">
			<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<mass value="${mass}"/>
				<xacro:insert_block name="inertia"/>
			</inertial>
			<visual>
				<xacro:insert_block name="visual_origin"/>
				<geometry>
					<mesh filename="package://dynamixel_description/${path_to_mesh}" />
				</geometry>
				<material name="gray">
					<color rgba="0.8 0.8 0.8 0.5"/>
				</material>
			</visual>
		</link>

    	<xacro:servo_XM430 name="${name}" parent="${name}_fr_FR12_S102K_" child="${child}" center_child="${center_child}" fixed_plane="${fixed_plane}"/>

	</xacro:macro>

</robot>